# Generated by Django 6.0.5 on 2026-05-23 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Общий счёт')),
                ('levels_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Пройдено уровней')),
                ('achievements_count', models.PositiveSmallIntegerField(default=0, verbose_name='Достижений')),
                ('rank', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ранг')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Запись лидерборда',
                'verbose_name_plural': 'Лидерборд',
                'ordering': ['rank'],
            },
        ),
    ]
