# Generated by Django 6.0.5 on 2026-05-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_anonymous_player',
            field=models.BooleanField(default=False, verbose_name='Анонимный игрок'),
        ),
        migrations.AddField(
            model_name='player',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Ключ сессии'),
        ),
    ]
