# Generated by Django 6.0.5 on 2026-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_is_anonymous_player_player_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID'),
        ),
    ]
