# Generated by Django 6.0.5 on 2026-05-23 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название (уз)')),
                ('description_uz', models.TextField(verbose_name='Описание (уз)')),
                ('icon', models.CharField(default='star', max_length=50, verbose_name='Иконка')),
                ('condition_type', models.CharField(choices=[('SCORE', 'Очки'), ('ACTION_COUNT', 'Количество действий'), ('LEVEL_COMPLETE', 'Завершение уровня'), ('INDICATOR', 'Значение индикатора')], max_length=20, verbose_name='Тип условия')),
                ('condition_value', models.JSONField(default=dict, help_text="ACTION_COUNT: {'action_key': 'plant_tree', 'count': 10}", verbose_name='Значение условия')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['condition_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='EcoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название (уз)')),
                ('description_uz', models.TextField(verbose_name='Описание (уз)')),
                ('category', models.CharField(choices=[('FLORA', 'Флора'), ('WATER', 'Вода'), ('WASTE', 'Отходы'), ('ENERGY', 'Энергия'), ('FAUNA', 'Фауна')], max_length=10, verbose_name='Категория')),
                ('score_value', models.PositiveIntegerField(default=10, verbose_name='Очки за действие')),
                ('air_impact', models.FloatField(default=0.0, verbose_name='Влияние на воздух')),
                ('water_impact', models.FloatField(default=0.0, verbose_name='Влияние на воду')),
                ('soil_impact', models.FloatField(default=0.0, verbose_name='Влияние на почву')),
                ('biodiversity_impact', models.FloatField(default=0.0, verbose_name='Влияние на биоразнообразие')),
                ('cooldown_seconds', models.PositiveIntegerField(default=5, verbose_name='Кулдаун (сек)')),
                ('sprite_key', models.CharField(default='default', max_length=50, verbose_name='Ключ спрайта')),
            ],
            options={
                'verbose_name': 'Экодействие',
                'verbose_name_plural': 'Экодействия',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер уровня')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название (уз)')),
                ('description_uz', models.TextField(verbose_name='Описание (уз)')),
                ('required_score', models.PositiveIntegerField(default=0, verbose_name='Очков для разблокировки')),
                ('map_config', models.JSONField(default=dict, verbose_name='Конфигурация карты')),
                ('ecosystem_initial', models.JSONField(default=dict, help_text='Пример: {"air": 30, "water": 25, "soil": 20, "biodiversity": 15}', verbose_name='Начальные значения экосистемы')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('position_x', models.FloatField(default=0.0, verbose_name='Позиция X')),
                ('position_y', models.FloatField(default=0.0, verbose_name='Позиция Y')),
                ('result_delta', models.JSONField(default=dict, verbose_name='Изменения индикаторов')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ecoaction', verbose_name='Действие')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='game.gamesession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Лог действий',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='ecoaction',
            name='unlock_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.level', verbose_name='Минимальный уровень'),
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('air_quality', models.FloatField(default=0.0, verbose_name='Качество воздуха')),
                ('water_purity', models.FloatField(default=0.0, verbose_name='Чистота воды')),
                ('soil_health', models.FloatField(default=0.0, verbose_name='Здоровье почвы')),
                ('biodiversity', models.FloatField(default=0.0, verbose_name='Биоразнообразие')),
                ('actions_performed', models.JSONField(default=dict, help_text='Пример: {"plant_tree": 5, "clean_water": 3}', verbose_name='Выполненные действия')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Прогресс',
                'verbose_name_plural': 'Прогресс игроков',
                'ordering': ['level__number'],
                'unique_together': {('player', 'level')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата разблокировки')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.achievement', verbose_name='Достижение')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Достижение игрока',
                'verbose_name_plural': 'Достижения игроков',
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
