# Generated by Django 6.0.5 on 2026-05-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoaction',
            name='cost',
            field=models.PositiveIntegerField(default=10, verbose_name='Стоимость (эко-монеты)'),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='world_state',
            field=models.JSONField(default=dict, help_text='{"placed_objects": [...], "resources": 75}', verbose_name='Состояние мира'),
        ),
    ]
