# Generated by Django 6.0.5 on 2026-05-24 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('game', '0002_ecoaction_cost_gameprogress_world_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoaction',
            name='unlock_level',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('SCORE', 'Очки'), ('ACTION_COUNT', 'Количество действий'), ('LEVEL_COMPLETE', 'Завершение уровня'), ('INDICATOR', 'Значение индикатора'), ('QUIZ_COUNT', 'Количество викторин'), ('STREAK', 'Серия ответов'), ('DAILY_STREAK', 'Ежедневная серия'), ('CATEGORY_MASTER', 'Мастер категории')], max_length=20, verbose_name='Тип условия'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_value',
            field=models.JSONField(default=dict, verbose_name='Значение условия'),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='actions_performed',
            field=models.JSONField(default=dict, verbose_name='Выполненные действия'),
        ),
        migrations.AlterField(
            model_name='gameprogress',
            name='world_state',
            field=models.JSONField(default=dict, verbose_name='Состояние мира'),
        ),
        migrations.AlterField(
            model_name='level',
            name='ecosystem_initial',
            field=models.JSONField(default=dict, verbose_name='Начальные значения экосистемы'),
        ),
        migrations.CreateModel(
            name='MiniGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('SORTING', 'Чiqindi saralash')], default='SORTING', max_length=20, verbose_name='Тип игры')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Правильных')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Всего предметов')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='Сыграно')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_game_scores', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Результат мини-игры',
                'verbose_name_plural': 'Результаты мини-игры',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(max_length=500, verbose_name='Вопрос (уз)')),
                ('category', models.CharField(choices=[('FLORA', 'Флора'), ('WATER', 'Вода'), ('WASTE', 'Отходы'), ('ENERGY', 'Энергия'), ('FAUNA', 'Фауна')], max_length=10, verbose_name='Категория')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Сложность (1-3)')),
                ('question_type', models.CharField(choices=[('MCQ', "Ko'p tanlovli"), ('TRUE_FALSE', "To'g'ri/Noto'g'ri"), ('SCENARIO', 'Senariy')], default='MCQ', max_length=10, verbose_name='Тип вопроса')),
                ('explanation_uz', models.TextField(verbose_name='Пояснение (уз)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение')),
                ('time_limit', models.PositiveSmallIntegerField(default=30, verbose_name='Лимит времени (сек)')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='education.educationalcontent', verbose_name='Связанная статья')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('bonus_score', models.PositiveIntegerField(default=50, verbose_name='Бонус (очки)')),
                ('questions', models.ManyToManyField(related_name='daily_challenges', to='game.question', verbose_name='Вопросы')),
            ],
            options={
                'verbose_name': 'Ежедневное задание',
                'verbose_name_plural': 'Ежедневные задания',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(max_length=300, verbose_name='Ответ (уз)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('QUICK', "Tezkor o'yin"), ('CATEGORY', "Kategoriya bo'yicha"), ('DAILY', 'Kunlik vazifa'), ('MARATHON', 'Marafon')], max_length=10, verbose_name='Режим')),
                ('category', models.CharField(blank=True, choices=[('FLORA', 'Флора'), ('WATER', 'Вода'), ('WASTE', 'Отходы'), ('ENERGY', 'Энергия'), ('FAUNA', 'Фауна')], max_length=10, null=True, verbose_name='Категория')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Всего вопросов')),
                ('max_streak', models.PositiveIntegerField(default=0, verbose_name='Макс. серия')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Сессия викторины',
                'verbose_name_plural': 'Сессии викторины',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('time_spent_ms', models.PositiveIntegerField(default=0, verbose_name='Время ответа (мс)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question', verbose_name='Вопрос')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.answer', verbose_name='Выбранный ответ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='game.quizsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Ответ в викторине',
                'verbose_name_plural': 'Ответы в викторине',
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.DeleteModel(
            name='ActionLog',
        ),
        migrations.DeleteModel(
            name='EcoAction',
        ),
    ]
