# Generated by Django 6.0.5 on 2026-05-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(max_length=300, verbose_name='Текст (уз)')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('category', models.CharField(choices=[('FLORA', 'Флора'), ('WATER', 'Вода'), ('WASTE', 'Отходы'), ('ENERGY', 'Энергия'), ('FAUNA', 'Фауна')], max_length=10, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Экофакт',
                'verbose_name_plural': 'Экофакты',
            },
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Заголовок (уз)')),
                ('body_uz', models.TextField(verbose_name='Текст (уз)')),
                ('category', models.CharField(choices=[('FLORA', 'Флора'), ('WATER', 'Вода'), ('WASTE', 'Отходы'), ('ENERGY', 'Энергия'), ('FAUNA', 'Фауна')], max_length=10, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='education/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Образовательная статья',
                'verbose_name_plural': 'Образовательные статьи',
                'ordering': ['order'],
            },
        ),
    ]
